id: TestExtractHTMLTables
version: -1
name: TestExtractHTMLTables
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 282e8a27-9a6c-4018-8cbe-c071d2a0c286
    type: start
    task:
      id: 282e8a27-9a6c-4018-8cbe-c071d2a0c286
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 245,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: ebe2c372-b615-4bdb-8682-8ca66ca0906d
    type: regular
    task:
      id: ebe2c372-b615-4bdb-8682-8ca66ca0906d
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 245,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 0e147bf0-2073-45a9-85f9-3b43a4a99e8d
    type: regular
    task:
      id: 0e147bf0-2073-45a9-85f9-3b43a4a99e8d
      version: -1
      name: ExtractHTMLTables with single one column table with header
      description: |-
        Find tables inside HTML and extract the contents into objects using the following logic:
        - If table has a single column, just create an array of strings from the values
        - If table has 2 columns and has no header row, treat the first column as key and second as value and create a table of key/value
        - If table has a header row, create a table of objects where attribute names are the headers
        - If table does not have a header row, create table of objects where attribute names are cell1, cell2, cell3...
      scriptName: ExtractHTMLTables
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      html:
        simple: <html><body><table><tr><th>kuku</th></tr><tr><td>a</td></tr><tr><td>1</td></tr></table></body></html>
      indexes: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 245,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 6b9a852b-bc6f-42a0-870a-bb3bd89770bc
    type: condition
    task:
      id: 6b9a852b-bc6f-42a0-870a-bb3bd89770bc
      version: -1
      name: Both values exist in array
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "6"
    scriptarguments:
      value:
        simple: '${HTMLTables=>val[0] == ''a'' && val[1] == ''1'' ? ''x'' : ''''}'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 245,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: f8213811-9e81-42fb-80c3-382c5b7c55cc
    type: regular
    task:
      id: f8213811-9e81-42fb-80c3-382c5b7c55cc
      version: -1
      name: Bad
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      value: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: daf05e8c-cd8f-4bf5-863a-56d1dedc9044
    type: regular
    task:
      id: daf05e8c-cd8f-4bf5-863a-56d1dedc9044
      version: -1
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 357.5,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 4fd1bb2d-7ee2-40ee-8924-d4e0147a2ef1
    type: regular
    task:
      id: 4fd1bb2d-7ee2-40ee-8924-d4e0147a2ef1
      version: -1
      name: ExtractHTMLTables with single one column table without header
      description: |-
        Find tables inside HTML and extract the contents into objects using the following logic:
        - If table has a single column, just create an array of strings from the values
        - If table has 2 columns and has no header row, treat the first column as key and second as value and create a table of key/value
        - If table has a header row, create a table of objects where attribute names are the headers
        - If table does not have a header row, create table of objects where attribute names are cell1, cell2, cell3...
      scriptName: ExtractHTMLTables
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      html:
        simple: <html><body><table><tr><td>a</td></tr><tr><td>1</td></tr></table></body></html>
      indexes: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 357.5,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: c0f1766f-0fd2-427c-8e36-037f8d816411
    type: condition
    task:
      id: c0f1766f-0fd2-427c-8e36-037f8d816411
      version: -1
      name: Both values exist in array
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "9"
    scriptarguments:
      value:
        simple: '${HTMLTables=>val[0] == ''a'' && val[1] == ''1'' ? ''x'' : ''''}'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 357.5,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: cfc7d163-9519-4efb-8147-bbc433eda996
    type: regular
    task:
      id: cfc7d163-9519-4efb-8147-bbc433eda996
      version: -1
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 470,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: e5515ca6-630c-4f00-8807-30391ba07fbd
    type: regular
    task:
      id: e5515ca6-630c-4f00-8807-30391ba07fbd
      version: -1
      name: ExtractHTMLTables with two columns and no headers
      description: |-
        Find tables inside HTML and extract the contents into objects using the following logic:
        - If table has a single column, just create an array of strings from the values
        - If table has 2 columns and has no header row, treat the first column as key and second as value and create a table of key/value
        - If table has a header row, create a table of objects where attribute names are the headers
        - If table does not have a header row, create table of objects where attribute names are cell1, cell2, cell3...
      scriptName: ExtractHTMLTables
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      html:
        simple: <html><body><table><tr><td>a</td><td>1</td></tr><tr><td>b</td><td>2</td></tr></table></body></html>
      indexes: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 470,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 8cf6edc6-283f-4d04-8591-d92efc197c8e
    type: condition
    task:
      id: 8cf6edc6-283f-4d04-8591-d92efc197c8e
      version: -1
      name: Both objects exist
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "12"
    scriptarguments:
      value:
        simple: ${HTMLTables(val.a == '1' && val.b == '2')}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 470,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: 36080405-8b93-42e0-80c9-02c4346c5090
    type: regular
    task:
      id: 36080405-8b93-42e0-80c9-02c4346c5090
      version: -1
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 582.5,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 04404071-e497-48bc-83c2-f54638ef0220
    type: regular
    task:
      id: 04404071-e497-48bc-83c2-f54638ef0220
      version: -1
      name: ExtractHTMLTables with two columns and headers
      description: |-
        Find tables inside HTML and extract the contents into objects using the following logic:
        - If table has a single column, just create an array of strings from the values
        - If table has 2 columns and has no header row, treat the first column as key and second as value and create a table of key/value
        - If table has a header row, create a table of objects where attribute names are the headers
        - If table does not have a header row, create table of objects where attribute names are cell1, cell2, cell3...
      scriptName: ExtractHTMLTables
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      html:
        simple: <html><body><table><tr><th>kuku</th><th>kaka</th></tr><tr><td>a</td><td>1</td></tr><tr><td>b</td><td>2</td></tr></table></body></html>
      indexes: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 582.5,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 434bb18f-db5a-4e0b-8c1b-e2cfd706d0ed
    type: condition
    task:
      id: 434bb18f-db5a-4e0b-8c1b-e2cfd706d0ed
      version: -1
      name: All objects exist
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "5"
    scriptarguments:
      value:
        simple: ${HTMLTables(val.kuku == 'a' && val.kaka == '1' || val.kuku == 'b'
          && val.kaka == '2')}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 582.5,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2340,
        "width": 912.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
