id: TestIsValueInArray
version: -1
name: TestIsValueInArray
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 777999b1-696d-4367-8959-cb6278b5e690
    type: start
    task:
      id: 777999b1-696d-4367-8959-cb6278b5e690
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": -112
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: ffb910f1-ecbf-493b-81db-a8084fee93eb
    type: regular
    task:
      id: ffb910f1-ecbf-493b-81db-a8084fee93eb
      version: -1
      name: Create array in context
      description: Find all users associated with a role
      scriptName: Set
      type: regular
      iscommand: false
      brand: Builtin
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      append: {}
      key:
        simple: myArray
      roles: {}
      value:
        simple: ${.=function(obj){return ['value1','value2','value3']}(val)}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 224
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: e9fa6303-e2b0-4af8-8229-b1b84f2cf7f1
    type: condition
    task:
      id: e9fa6303-e2b0-4af8-8229-b1b84f2cf7f1
      version: -1
      name: Check existing value
      description: Look for value in a list
      scriptName: IsValueInArray
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "3"
      "yes":
      - "4"
    scriptarguments:
      array:
        simple: ${myArray}
      left: {}
      list:
        simple: ${myList}
      right: {}
      value:
        simple: value2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 398
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 3dfc40fa-249f-4541-8ad0-5d549ffeb021
    type: regular
    task:
      id: 3dfc40fa-249f-4541-8ad0-5d549ffeb021
      version: -1
      name: Bad...
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 22,
          "y": 571
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: d6f5b235-1780-4775-87e9-dd0d67a37ef6
    type: condition
    task:
      id: d6f5b235-1780-4775-87e9-dd0d67a37ef6
      version: -1
      name: Check a non exist value
      scriptName: IsValueInArray
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "6"
      "yes":
      - "5"
    scriptarguments:
      array:
        simple: ${myArray}
      left: {}
      list:
        simple: ${myList}
      right: {}
      value:
        simple: value5
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 697
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 49e92eb9-eea7-45bc-848b-84c6f6408cfc
    type: regular
    task:
      id: 49e92eb9-eea7-45bc-848b-84c6f6408cfc
      version: -1
      name: Bad...
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 46,
          "y": 875
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 636b7dfe-543f-4b53-8396-3a9863e14f20
    type: condition
    task:
      id: 636b7dfe-543f-4b53-8396-3a9863e14f20
      version: -1
      name: 'Check two equal strings '
      scriptName: IsValueInArray
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "7"
      "yes":
      - "8"
    scriptarguments:
      array:
        simple: value
      left: {}
      list:
        simple: value
      right: {}
      value:
        simple: value
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1012
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 03ff4c6d-a017-45a7-85ac-58e6fd3a1d0c
    type: regular
    task:
      id: 03ff4c6d-a017-45a7-85ac-58e6fd3a1d0c
      version: -1
      name: Bad...
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 46,
          "y": 1173
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 59715a06-d89b-4395-84aa-54f17fbccbff
    type: condition
    task:
      id: 59715a06-d89b-4395-84aa-54f17fbccbff
      version: -1
      name: 'Check two non equal strings '
      scriptName: IsValueInArray
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "11"
      "yes":
      - "9"
    scriptarguments:
      array:
        simple: value
      left: {}
      list:
        simple: value
      right: {}
      value:
        simple: other
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1351
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 0787c392-ea4a-4e5e-877b-7761772e8b8d
    type: regular
    task:
      id: 0787c392-ea4a-4e5e-877b-7761772e8b8d
      version: -1
      name: Bad...
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 46,
          "y": 1519
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 91141070-63e6-4c93-875a-1f37c2282b8c
    type: condition
    task:
      id: 91141070-63e6-4c93-875a-1f37c2282b8c
      version: -1
      name: Check empty array
      scriptName: IsValueInArray
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "13"
      "yes":
      - "12"
    scriptarguments:
      array: {}
      left: {}
      list:
        simple: value
      right: {}
      value:
        simple: other
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1729
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: 9b754591-1e61-499a-8c5d-ecdbe985ca1b
    type: regular
    task:
      id: 9b754591-1e61-499a-8c5d-ecdbe985ca1b
      version: -1
      name: Bad...
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 46,
          "y": 1893
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: e11bf068-4e20-489f-8d0b-d51e419da6ee
    type: condition
    task:
      id: e11bf068-4e20-489f-8d0b-d51e419da6ee
      version: -1
      name: Check empty value
      scriptName: IsValueInArray
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "14"
    scriptarguments:
      array:
        simple: ${myArray}
      left: {}
      list:
        simple: value
      right: {}
      value: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 2056
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: db295bfe-c0c3-479e-8092-485ecf2c2860
    type: regular
    task:
      id: db295bfe-c0c3-479e-8092-485ecf2c2860
      version: -1
      name: Bad...
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 46,
          "y": 2225
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2432,
        "width": 808,
        "x": 22,
        "y": -112
      }
    }
  }
inputs: []
outputs: []
