id: LanguageDetect-Test
version: -1
name: LanguageDetect-Test
description: Testing LanguageDetect script
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d6a21f32-7243-49dc-825f-daab105c4c22
    type: start
    task:
      id: d6a21f32-7243-49dc-825f-daab105c4c22
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 8fa2ec38-1c98-44f3-8e81-a810b4e2fa06
    type: regular
    task:
      id: 8fa2ec38-1c98-44f3-8e81-a810b4e2fa06
      version: -1
      name: Detect english
      scriptName: LanguageDetect
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      text:
        simple: Hello World
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: c457a464-28e3-40f7-8547-0b51014fddbc
    type: condition
    task:
      id: c457a464-28e3-40f7-8547-0b51014fddbc
      version: -1
      name: Check if we found English
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    scriptarguments:
      value:
        simple: ${langDetect(val.lang=='en')}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: ec3eaff8-e329-4fc2-81ca-fe3cf31d7519
    type: regular
    task:
      id: ec3eaff8-e329-4fc2-81ca-fe3cf31d7519
      version: -1
      name: Sleep for 3 minutes
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      seconds:
        simple: "60"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: f2c79dad-f6d7-4f33-85b3-69cba6e99b4b
    type: regular
    task:
      id: f2c79dad-f6d7-4f33-85b3-69cba6e99b4b
      version: -1
      name: Detect english once again
      scriptName: LanguageDetect
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      text:
        simple: Hello World
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: e8b75bff-d587-491b-8c0c-1b3fc054c80e
    type: regular
    task:
      id: e8b75bff-d587-491b-8c0c-1b3fc054c80e
      version: -1
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 940,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
