id: HTTPListRedirects Basic Test
version: -1
name: HTTPListRedirects Basic Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 3062ba21-41ac-41dc-8262-62e34a548796
    type: start
    task:
      id: 3062ba21-41ac-41dc-8262-62e34a548796
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: d6e2f60e-0535-46a5-8b8c-003461d77d3c
    type: regular
    task:
      id: d6e2f60e-0535-46a5-8b8c-003461d77d3c
      version: -1
      name: HTTPListRedirects
      description: List the redirects for a given URL
      scriptName: HTTPListRedirects
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      extend-context: {}
      url:
        simple: http://httpbin.org/redirect/3
      useHead:
        simple: "true"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 9823454b-13c7-4546-8b72-19bae418b789
    type: condition
    task:
      id: 9823454b-13c7-4546-8b72-19bae418b789
      version: -1
      name: AreValuesEqual
      description: Check whether the values provided in arguments are equal.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    scriptarguments:
      left:
        simple: ${.=val.URL.length}
      right:
        simple: "4"
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 415,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
