id: listExecutedCommands-Test
version: -1
name: listExecutedCommands-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 605083fa-ff59-44be-86db-75a0e2e771ac
    type: start
    task:
      id: 605083fa-ff59-44be-86db-75a0e2e771ac
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: f3cf0c28-9faf-4823-83b4-763071d7a1e8
    type: regular
    task:
      id: f3cf0c28-9faf-4823-83b4-763071d7a1e8
      version: -1
      name: Print Hello World
      description: Prints text to war room (Markdown supprted)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      value:
        simple: Hello World
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 5df3f96a-e9ed-4995-8a73-07ba9f61e488
    type: regular
    task:
      id: 5df3f96a-e9ed-4995-8a73-07ba9f61e488
      version: -1
      name: Get list of manual commands
      scriptName: listExecutedCommands
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      source:
        simple: Manual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 827688c9-7ea0-44b5-8f1c-8478001c0c5a
    type: regular
    task:
      id: 827688c9-7ea0-44b5-8f1c-8478001c0c5a
      version: -1
      name: Save response to context
      description: "Takes the comments of a given entry ID and stores them in the
        incident context, under a provided context key. \nFor accessing the last executed
        task's comments, provide ${lastCompletedTaskEntries.[0]} as the value for
        the entryId input parameter."
      scriptName: commentsToContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      contextKey:
        simple: noData
      entryId:
        simple: ${lastCompletedTaskEntries}
      listSeperator: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: c3d77843-815d-49aa-83f3-2a074101bab6
    type: condition
    task:
      id: c3d77843-815d-49aa-83f3-2a074101bab6
      version: -1
      name: Check that we didn't get any commands
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "5"
    scriptarguments:
      left:
        simple: ${noData=val.trim()}
      right:
        simple: No commands found
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 719
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 4bbb6116-826d-4fbd-8c14-ce86ddffea0f
    type: regular
    task:
      id: 4bbb6116-826d-4fbd-8c14-ce86ddffea0f
      version: -1
      name: Get playbook commands
      scriptName: listExecutedCommands
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      source:
        simple: Playbook
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 3611a982-0483-40c8-8274-418ce11abd9b
    type: regular
    task:
      id: 3611a982-0483-40c8-8274-418ce11abd9b
      version: -1
      name: Save response to context
      scriptName: commentsToContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      contextKey:
        simple: withData
      entryId:
        simple: ${lastCompletedTaskEntries}
      listSeperator: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1069
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: a00d600f-395a-4879-87b1-86bc87e27373
    type: condition
    task:
      id: a00d600f-395a-4879-87b1-86bc87e27373
      version: -1
      name: Check that we got commands
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    scriptarguments:
      left:
        simple: ${withData=val.trim()}
      right:
        simple: No commands found
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1290,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
