id: ExposeIncidentOwner-Test
version: -1
name: ExposeIncidentOwner-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 148d1add-bc11-4af2-85ec-bb2bcac1a7ae
    type: start
    task:
      id: 148d1add-bc11-4af2-85ec-bb2bcac1a7ae
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: ef61cf27-8e97-40dd-850a-4dfb46e8f135
    type: regular
    task:
      id: ef61cf27-8e97-40dd-850a-4dfb46e8f135
      version: -1
      name: AssignAnalystToIncident
      description: |-
        Assign analyst to incident.
        By default,  the analyst is picked randomly from the available users, according to the provided roles (if no roles provided, will fetch all users).
        Otherwise, the analyst will be picked according to the 'assignBy' arguments.
        machine-learning: DBot will calculated and decide who is the best analyst for the job.
        top-user: The user that is most commonly owns this type of incident
        less-busy-user: The less busy analyst will be picked to be the incident owner.
        online: The analyst is picked randomly from all online analysts, according to the provided roles (if no roles provided, will fetch all users).
      scriptName: AssignAnalystToIncident
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      assignBy: {}
      email: {}
      roles: {}
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 18f0b1bb-06c1-4a78-87e1-36c597036d53
    type: regular
    task:
      id: 18f0b1bb-06c1-4a78-87e1-36c597036d53
      version: -1
      name: ExposeIncidentOwner
      description: Expose the incident owner into IncidentOwner context key
      scriptName: ExposeIncidentOwner
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    results:
    - IncidentOwner
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 3261b0cd-4023-47f1-8f98-83302842f9fa
    type: condition
    task:
      id: 3261b0cd-4023-47f1-8f98-83302842f9fa
      version: -1
      name: AreValuesEqual
      description: Check whether the values provided in arguments are equal.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "5"
    scriptarguments:
      left:
        simple: ${incident.owner}
      right:
        simple: ${IncidentOwner.username}
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 885e19ec-5cdf-43f5-8a1b-542b78630d0a
    type: regular
    task:
      id: 885e19ec-5cdf-43f5-8a1b-542b78630d0a
      version: -1
      name: Error
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 765,
        "width": 595,
        "x": 265,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
