id: Zimperium_Test
name: Zimperium_Test
version: -1
fromversion: 5.0.0
description: |-
  A test playbook for Zimperium.
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: '0'
    type: start
    task:
      id: '0'
      version: -1
      name: ''
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    view: '{"position": {"x": 50, "y": 50}}'
    note: false
    timertriggers: []
    ignoreworker: false
  '1':
    id: 1
    taskid: '1'
    type: regular
    task:
      id: '1'
      version: -1
      name: DeleteContext
      description: ''
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      all:
        simple: yes
    separatecontext: false
    view: '{"position": {"x": 50, "y": 200}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '2':
    id: 2
    taskid: '2'
    type: regular
    task:
      id: '2'
      version: -1
      name: zimperium-events-search
      description: ''
      script: '|||zimperium-events-search'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '3'
    scriptarguments: {}
    separatecontext: false
    view: '{"position": {"x": 50, "y": 400}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '3':
    id: '3'
    taskid: '3'
    type: condition
    task:
      id: '3'
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      description: ''
      brand: ''
    nexttasks:
      yes:
      - '4'
    separatecontext: false
    conditions:
    - label: yes
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: hello
            iscontext: true
    view: '{"position": {"x": 50, "y": 600}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '4':
    id: 4
    taskid: '4'
    type: regular
    task:
      id: '4'
      version: -1
      name: zimperium-users-search
      description: ''
      script: '|||zimperium-users-search'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '5'
    scriptarguments: {}
    separatecontext: false
    view: '{"position": {"x": 50, "y": 800}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '5':
    id: 5
    taskid: '5'
    type: regular
    task:
      id: '5'
      version: -1
      name: zimperium-user-get-by-id
      description: ''
      script: '|||zimperium-user-get-by-id'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '6'
    scriptarguments: {}
    separatecontext: false
    view: '{"position": {"x": 50, "y": 1000}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '6':
    id: 6
    taskid: '6'
    type: regular
    task:
      id: '6'
      version: -1
      name: zimperium-devices-search
      description: ''
      script: '|||zimperium-devices-search'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '7'
    scriptarguments: {}
    separatecontext: false
    view: '{"position": {"x": 50, "y": 1200}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '7':
    id: 7
    taskid: '7'
    type: regular
    task:
      id: '7'
      version: -1
      name: zimperium-device-get-by-id
      description: ''
      script: '|||zimperium-device-get-by-id'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '8'
    scriptarguments: {}
    separatecontext: false
    view: '{"position": {"x": 50, "y": 1400}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '8':
    id: 8
    taskid: '8'
    type: regular
    task:
      id: '8'
      version: -1
      name: zimperium-devices-get-last-updated
      description: ''
      script: '|||zimperium-devices-get-last-updated'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '9'
    scriptarguments: {}
    separatecontext: false
    view: '{"position": {"x": 50, "y": 1600}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '9':
    id: 9
    taskid: '9'
    type: regular
    task:
      id: '9'
      version: -1
      name: zimperium-app-classification-get
      description: ''
      script: '|||zimperium-app-classification-get'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '10'
    scriptarguments: {}
    separatecontext: false
    view: '{"position": {"x": 50, "y": 1800}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '10':
    id: 10
    taskid: '10'
    type: regular
    task:
      id: '10'
      version: -1
      name: zimperium-report-get
      description: ''
      script: '|||zimperium-report-get'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '11'
    scriptarguments: {}
    separatecontext: false
    view: '{"position": {"x": 50, "y": 2000}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '11':
    id: 11
    taskid: '11'
    type: regular
    task:
      id: '11'
      version: -1
      name: zimperium-app-upload-for-analysis
      description: ''
      script: '|||zimperium-app-upload-for-analysis'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '12'
    scriptarguments: {}
    separatecontext: false
    view: '{"position": {"x": 50, "y": 2200}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  '12':
    id: '12'
    taskid: '12'
    type: title
    task:
      id: '12'
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ''
      description: ''
    separatecontext: false
    view: '{"position": {"x": 50, "y": 2400}}'
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
view: '{"linkLabelsPosition": {}, "paper": {"dimensions": {"height": 200, "width":
  380, "x": 50, "y": 50}}}'
inputs: []
outputs: []
