id: Nmap - Test
version: -1
name: Nmap - Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 1c0bb526-4f44-4095-885d-de81a8bf51ca
    type: start
    task:
      id: 1c0bb526-4f44-4095-885d-de81a8bf51ca
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 6b263c77-b8d5-4ef4-8e15-5ad8b5e273f9
    type: regular
    task:
      id: 6b263c77-b8d5-4ef4-8e15-5ad8b5e273f9
      version: -1
      name: nmap-scan
      description: Scan targets with the given parameters
      script: nmap|||nmap-scan
      type: regular
      iscommand: true
      brand: nmap
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      options:
        simple: -sV
      targets:
        simple: scanme.nmap.org
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: ca6856eb-daaf-44ef-84be-f695c7f65a72
    type: condition
    task:
      id: ca6856eb-daaf-44ef-84be-f695c7f65a72
      version: -1
      name: Exists
      description: Check if a given value exists in the context. Will return 'no'
        for empty empty arrays. To be used mostly with DQ and selectors.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "4"
    scriptarguments:
      value:
        simple: ${NMAP.Scan.Hosts.Services.Port(val==22)}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 375
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: b2541e86-0e15-4931-8755-54938aac2a29
    type: regular
    task:
      id: b2541e86-0e15-4931-8755-54938aac2a29
      version: -1
      name: Oops, problem
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      value:
        simple: Service not found
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 970,
          "y": 660
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: e66ba8b6-27d4-46b6-8be3-02ee553cb086
    type: regular
    task:
      id: e66ba8b6-27d4-46b6-8be3-02ee553cb086
      version: -1
      name: nmap-scan
      description: Scan targets with the given parameters
      script: '|||nmap-scan'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      options:
        simple: -sn
      targets:
        simple: 8.8.8.8
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 970,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: e1ef6f98-d9e7-43b0-8eb1-81c442286420
    type: condition
    task:
      id: e1ef6f98-d9e7-43b0-8eb1-81c442286420
      version: -1
      name: check Hostname
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: NMAP
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: NMAP.Scan.Hosts.Address
                      iscontext: true
                    right:
                      value:
                        simple: 8.8.8.8
                accessor: Scan.Hosts.Hostname
            iscontext: true
          right:
            value:
              simple: dns.google
    view: |-
      {
        "position": {
          "x": 970,
          "y": 375
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {
      "2_4_no": 0.26
    },
    "paper": {
      "dimensions": {
        "height": 705,
        "width": 1085,
        "x": 265,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
