version: 2
jobs:
  build:
    docker:
      - image: devdemisto/content-build:1.0.0.132 # disable-secrets-detection
    environment:
      CONTENT_VERSION: "19.3.0"
      GIT_SHA1: "1e217e427fe9fa4816f4d5257a54d553eba65ee9" # guardrails-disable-line disable-secrets-detection
    steps:
      - checkout
      - run:
          name: Prepare Environment
          command: |
              echo 'export CIRCLE_ARTIFACTS="/home/circleci/project/artifacts"' >> $BASH_ENV
              echo 'export PATH="/home/circleci/.local/bin:${PATH}"' >> $BASH_ENV
              source $BASH_ENV
              sudo mkdir -p -m 777 $CIRCLE_ARTIFACTS
              chmod +x ./Tests/scripts/*
              chmod +x ./Tests/lastest_server_build_scripts/*
      - add_ssh_keys:
          fingerprints:
              - "02:df:a5:6a:53:9a:f5:5d:bd:a6:fc:b2:db:9b:c9:47" # disable-secrets-detection
      - run:
          name: Validate Files and Yaml
          command: |
              ./Tests/scripts/pyflake.sh
              python ./Tests/scripts/validate_files_structure.py -c true
      - run:
          name: Configure Test Filter
          command: |
              [ -n "${NIGHTLY}" ] && IS_NIGHTLY=true || IS_NIGHTLY=false
              python ./Tests/scripts/configure_tests.py -n $IS_NIGHTLY
      - run:
          name: Build Content Descriptor
          command: ./setContentDescriptor.sh $CIRCLE_BUILD_NUM $GIT_SHA1 $CONTENT_VERSION
      - run:
          name: Common Server Documentation
          command: ./Documentation/commonServerDocs.sh
      - run:
          name: Create Content Artifacts
          command: python content_creator.py $CIRCLE_ARTIFACTS