id: TAXII 2 Feed Test
version: -1
name: TAXII 2 Feed Test
fromversion: 5.5.0
starttaskid: "0"
description: ""
tasks:
  "0":
    id: "0"
    taskid: eabafc0b-19a5-4ac7-89ab-5cd36e26680f
    type: start
    task:
      id: eabafc0b-19a5-4ac7-89ab-5cd36e26680f
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 9cb3d98b-1fed-4019-849f-2c347b821212
    type: regular
    task:
      id: 9cb3d98b-1fed-4019-849f-2c347b821212
      version: -1
      name: taxii2-get-collections
      description: Get the list of collections from the discovery service.
      script: FeedTAXII2|||taxii2-get-collections
      type: regular
      iscommand: true
      brand: FeedTAXII2
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 8fd496b1-4a32-4bfd-8c93-aa639603548b
    type: regular
    task:
      id: 8fd496b1-4a32-4bfd-8c93-aa639603548b
      version: -1
      name: taxii2-get-indicators
      description: Allows you to test your feed, and to make sure you can fetch indicators
        successfuly .
      script: FeedTAXII2|||taxii2-get-indicators
      type: regular
      iscommand: true
      brand: FeedTAXII2
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      added_after: {}
      limit:
        simple: "100"
      raw: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 620
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: e38f5ad5-4167-4186-8cab-c76cc60621e0
    type: condition
    task:
      id: e38f5ad5-4167-4186-8cab-c76cc60621e0
      version: -1
      name: Assert collections fetched
      type: condition
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: TAXII2.Collections.ID
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: TAXII2.Collections.Name
            iscontext: true
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 9bd13823-c3e2-4b6a-8eab-9397071a1a7b
    type: condition
    task:
      id: 9bd13823-c3e2-4b6a-8eab-9397071a1a7b
      version: -1
      name: Assert indicators fetched
      type: condition
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: TAXII2.Indicators.type
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: TAXII2.Indicators.value
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: TAXII2.Indicators.rawJSON
            iscontext: true
    view: |-
      {
        "position": {
          "x": 450,
          "y": 810
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 2f63bcb5-e623-4ca5-8361-6d2e7d604c7a
    type: title
    task:
      id: 2f63bcb5-e623-4ca5-8361-6d2e7d604c7a
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1000
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1015,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
