id: PCAP Analysis
version: -1
fromversion: 5.0.0
name: PCAP Analysis
description: 'This playbook leverages all of the PCAP miner automation capabilities
  including: 
  * Search for specific values in a PCAP file
  * Parse and enrich detected indicators found by the search such as IP addresses, URLs, email addresses and domains.
  * Carve (extract) files found in the http, smb and other protocols and perform enrichment and detonation.'
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 77d3598c-9650-48e9-8715-05088482ce0c
    type: start
    task:
      id: 77d3598c-9650-48e9-8715-05088482ce0c
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 70
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 4b05ded5-c86e-4804-867d-b7f89f8dad28
    type: playbook
    task:
      id: 4b05ded5-c86e-4804-867d-b7f89f8dad28
      version: -1
      name: PCAP Parsing And Indicator Enrichment
      playbookName: PCAP Parsing And Indicator Enrichment
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      ExtractStringWithRegex: {}
      ExtractStrings:
        simple: "False"
      InternalDomainName: {}
      InternalEmailDomainName: {}
      InternalIPRange: {}
      PcapFileEntryID:
        complex:
          root: File
          filters:
          - - operator: inList
              left:
                value:
                  simple: File.Name
                iscontext: true
              right:
                value:
                  simple: incident.pcapfile.name
                iscontext: true
            - operator: isEqualString
              left:
                value:
                  simple: File.Extension
                iscontext: true
              right:
                value:
                  simple: pcap
            - operator: isEqualString
              left:
                value:
                  simple: File.Extension
                iscontext: true
              right:
                value:
                  simple: cap
            - operator: isEqualString
              left:
                value:
                  simple: File.Extension
                iscontext: true
              right:
                value:
                  simple: pcapng
          accessor: EntryID
      PcapFilter:
        simple: ${PcapQuery}
      ProtocolsToOutput:
        complex:
          root: DetectedProtocols
          transformers:
          - operator: toUpperCase
          - operator: join
            args:
              separator:
                value:
                  simple: ','
      RsaDecryptKeyEntryID:
        complex:
          root: File
          filters:
          - - operator: inList
              left:
                value:
                  simple: File.Name
                iscontext: true
              right:
                value:
                  simple: incident.pcapencryptionkey.name
                iscontext: true
            - operator: isEqualString
              left:
                value:
                  simple: File.Extension
                iscontext: true
              right:
                value:
                  simple: key
          accessor: EntryID
      WhichIndicatorTypeToEnrich:
        simple: ip,url,domain,email
      WpaPassword: {}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": -30,
          "y": 990
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 5ba04b3e-5c95-4741-8dd3-1812b5afcf4f
    type: title
    task:
      id: 5ba04b3e-5c95-4741-8dd3-1812b5afcf4f
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: e63969a9-ccb8-48c0-8f40-f32ff4ed93ce
    type: condition
    task:
      id: e63969a9-ccb8-48c0-8f40-f32ff4ed93ce
      version: -1
      name: Is there a PCAP file?
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: inputs.PcapFileEntryID
            iscontext: true
    view: |-
      {
        "position": {
          "x": 450,
          "y": 220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: c1089a55-d51d-4914-8359-4d60ed31f719
    type: condition
    task:
      id: c1089a55-d51d-4914-8359-4d60ed31f719
      version: -1
      name: Run parsing and enrichment?
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: inputs.RunParsingAndEnrichment
            iscontext: true
          right:
            value:
              simple: "true"
    view: |-
      {
        "position": {
          "x": 220,
          "y": 570
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 38221a90-2312-4d0d-83a5-51a82e05d425
    type: condition
    task:
      id: 38221a90-2312-4d0d-83a5-51a82e05d425
      version: -1
      name: Were there results from the search?
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: DetectedProtocols
            iscontext: true
    view: |-
      {
        "position": {
          "x": 100,
          "y": 790
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 490092a9-a0ba-40b4-8778-4784b70c19ed
    type: playbook
    task:
      id: 490092a9-a0ba-40b4-8778-4784b70c19ed
      version: -1
      name: PCAP Search
      description: This playbook is used to parse and search within PCAP files. Supported
        file types are pcap, cap, pcapng. The playbook can handle one PCAP file per
        incident. The user inputs which objects the playbook should search for in
        the PCAP. The values to search are IP addresses, CIDR ranges, and TCP or UDP
        ports or protocols. In the event that more than one input type was specified,
        specify in the QueryOperator input (such as IP addresses and TCP ports) if
        the PCAP filter query will use an AND or an OR operator between the inputs.  Another
        option is to use advanced filters just like in Wireshark to use refined filters
        or for objects not specified in other inputs. Additional inputs allow the
        user to provide the WPA password for decrypting 802.11 (wireless) traffic
        and adding an RSA certificate to decrypt SSL traffic. To display the results
        within the relevant incident fields, the playbook needs to run in a PCAP Analysis
        incident type. For handling of PCAP files larger than 30 MB, refer to the
        PcapMinerV2 documentation.
      playbookName: PCAP Search
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
      - "10"
    scriptarguments:
      AdvancedSearchFilter: {}
      IPAddressToSearch: {}
      InternalIPRange: {}
      PcapFileEntryID:
        complex:
          root: File
          filters:
          - - operator: inList
              left:
                value:
                  simple: File.Name
                iscontext: true
              right:
                value:
                  simple: incident.pcapfile.name
                iscontext: true
            - operator: isEqualString
              left:
                value:
                  simple: File.Extension
                iscontext: true
              right:
                value:
                  simple: pcap
            - operator: isEqualString
              left:
                value:
                  simple: File.Extension
                iscontext: true
              right:
                value:
                  simple: cap
            - operator: isEqualString
              left:
                value:
                  simple: File.Extension
                iscontext: true
              right:
                value:
                  simple: pcapng
          accessor: EntryID
      ProtocolToSearch: {}
      QueryOperator:
        simple: and
      RsaDecryptKeyEntryID:
        complex:
          root: File
          filters:
          - - operator: inList
              left:
                value:
                  simple: File.Name
                iscontext: true
              right:
                value:
                  simple: incident.pcapencryptionkey.name
                iscontext: true
            - operator: isEqualString
              left:
                value:
                  simple: File.Extension
                iscontext: true
              right:
                value:
                  simple: key
          accessor: EntryID
      TCPPortsToSearch: {}
      UDPPortsToSearch: {}
      WpaPassword: {}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 220,
          "y": 400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 38a2770c-4b5a-4f45-8c0f-b0024345ac04
    type: playbook
    task:
      id: 38a2770c-4b5a-4f45-8c0f-b0024345ac04
      version: -1
      name: PCAP File Carving
      playbookName: PCAP File Carving
      type: playbook
      iscommand: false
      brand: ""
      description: This playbook is used to carve (extract) files from within PCAP
        files and perform enrichment and detonation of the extracted files. Supported
        PCAP file types are pcap, cap, pcapng. The playbook can handle one PCAP file
        per incident. Additional inputs allow the user to provide the WPA password
        for decrypting 802.11 (wireless) traffic and add an RSA certificate to
        decrypt SSL traffic. To display the results within the relevant incident fields,
        the playbook needs to run in a PCAP Analysis incident type. For handling of
        PCAP files larger than 30 MB, refer to the PcapMinerV2 documentation.
    nexttasks:
      '#none#':
      - "3"
    separatecontext: true
    view: |-
      {
        "position": {
          "x": 940,
          "y": 990
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 88694368-25c0-4868-86ee-a97bbab9c0b4
    type: condition
    task:
      id: 88694368-25c0-4868-86ee-a97bbab9c0b4
      version: -1
      name: Were protocols containing files were found?
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: inList
          left:
            value:
              simple: DetectedProtocols
            iscontext: true
          right:
            value:
              simple: "1"
    view: |-
      {
        "position": {
          "x": 810,
          "y": 790
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 26809aa3-136f-49e8-8ef6-9d661816df6b
    type: condition
    task:
      id: 26809aa3-136f-49e8-8ef6-9d661816df6b
      version: -1
      name: Run file carving?
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "9"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: inputs.RunFileCarving
            iscontext: true
          right:
            value:
              simple: "true"
    view: |-
      {
        "position": {
          "x": 680,
          "y": 570
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1195,
        "width": 1350,
        "x": -30,
        "y": 70
      }
    }
  }
inputs:
- key: PcapFileEntryID
  value:
    complex:
      root: File
      filters:
      - - operator: inList
          left:
            value:
              simple: File.Name
            iscontext: true
          right:
            value:
              simple: incident.pcapfile.name
            iscontext: true
        - operator: isEqualString
          left:
            value:
              simple: File.Extension
            iscontext: true
          right:
            value:
              simple: pcap
        - operator: isEqualString
          left:
            value:
              simple: File.Extension
            iscontext: true
          right:
            value:
              simple: cap
        - operator: isEqualString
          left:
            value:
              simple: File.Extension
            iscontext: true
          right:
            value:
              simple: pcapng
      accessor: EntryID
  required: false
  description: This input specifies the file entry ID for the PCAP file if the user
    provided the file in the incident. One PCAP file can run per incident.
  playbookInputQuery:
- key: RunParsingAndEnrichment
  value:
    simple: "true"
  required: false
  description: This input specifies whether to run the parsing and enrichment playbook.
    Values can be true or any other value for false
  playbookInputQuery:
- key: RunFileCarving
  value:
    simple: "true"
  required: false
  description: This input specifies whether to run the file carving playbook. Values can
    be true or any other value for false
  playbookInputQuery:
- key: RsaDecryptKeyEntryID
  value:
    complex:
      root: File
      filters:
      - - operator: inList
          left:
            value:
              simple: File.Name
            iscontext: true
          right:
            value:
              simple: incident.pcapencryptionkey.name
            iscontext: true
        - operator: isEqualString
          left:
            value:
              simple: File.Extension
            iscontext: true
          right:
            value:
              simple: key
      accessor: EntryID
  required: false
  description: This input specifies the file entry ID for the RSA decrypt key if the
    user provided the key in the incident.
  playbookInputQuery:
outputs: []
tests:
- No tests (auto formatted)
