id: forcepoint test
version: -1
name: forcepoint test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e65b21ec-c1fb-404e-8bd8-2003e36f11e6
    type: start
    task:
      id: e65b21ec-c1fb-404e-8bd8-2003e36f11e6
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: a5a05f1d-ac1e-4b00-885f-d17739c10f9b
    type: regular
    task:
      id: a5a05f1d-ac1e-4b00-885f-d17739c10f9b
      version: -1
      name: Delete Context
      description: 'Deletes previous context '
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 1761af03-4d2e-4ff6-825c-467ecfb15549
    type: regular
    task:
      id: 1761af03-4d2e-4ff6-825c-467ecfb15549
      version: -1
      name: Add new 'TEST' category
      description: Will Add new API-managed category.
      script: Forcepoint|||fp-add-category
      type: regular
      iscommand: true
      brand: Forcepoint
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      categoryDescription: {}
      categoryName:
        simple: NEW TEST CATEGORY
      parent: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: c7b2a8d7-3f6b-41af-8acc-f7faf6307b1b
    type: regular
    task:
      id: c7b2a8d7-3f6b-41af-8acc-f7faf6307b1b
      version: -1
      name: Get new category details
      description: Query by category name
      script: Forcepoint|||fp-get-category-detailes
      type: regular
      iscommand: true
      brand: Forcepoint
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      categoryId: {}
      categoryName:
        simple: ${Forcepoint.AddCategory.CategoryName}
      extend-context: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 6d06cdab-aab2-4d44-8b8e-82ff0d8db139
    type: regular
    task:
      id: 6d06cdab-aab2-4d44-8b8e-82ff0d8db139
      version: -1
      name: Add URLs to 'TEST' category
      description: |-
        Using the ID associated with the new category.
        Add 'https://test.com', 'http://dem.com' to category URL list.
      script: Forcepoint|||fp-add-address-to-category
      type: regular
      iscommand: true
      brand: Forcepoint
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      categoryID: {}
      categoryName:
        simple: ${Forcepoint.CategoryDetails.CategoryName}
      ips: {}
      urls:
        simple: https://test.com,http://dem.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 69c7eb99-8e54-42a9-840e-28435cb5e579
    type: regular
    task:
      id: 69c7eb99-8e54-42a9-840e-28435cb5e579
      version: -1
      name: Delete URL from 'TEST' category
      description: Delete https://test.com from the category URL list
      script: Forcepoint|||fp-delete-address-from-category
      type: regular
      iscommand: true
      brand: Forcepoint
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      categoryID:
        simple: ${Forcepoint.CategoryDetails.CategoryID}
      categoryName: {}
      ips: {}
      urls:
        simple: https://test.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 2c7ccf7c-2f1e-43ae-89a2-8375575aef74
    type: regular
    task:
      id: 2c7ccf7c-2f1e-43ae-89a2-8375575aef74
      version: -1
      name: Get 'TEST' category details after alterations
      script: Forcepoint|||fp-get-category-detailes
      type: regular
      iscommand: true
      brand: Forcepoint
      description: ''
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      categoryId:
        simple: ${Forcepoint.CategoryDetails.CategoryID}
      categoryName: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: e265c9ba-ef5e-473d-852c-e680ee948a8b
    type: regular
    task:
      id: e265c9ba-ef5e-473d-852c-e680ee948a8b
      version: -1
      name: Delete 'TEST' category
      description: Using the category ID
      script: Forcepoint|||fp-delete-categories
      type: regular
      iscommand: true
      brand: Forcepoint
    scriptarguments:
      categoryIDs:
        simple: ${Forcepoint.CategoryDetails.CategoryID}
      categoryNames: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2315
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 08532f9c-3c23-4382-8d4e-17cd76a4d11e
    type: regular
    task:
      id: 08532f9c-3c23-4382-8d4e-17cd76a4d11e
      version: -1
      name: Set urls
      description: Sets a value into the context with the given context key
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      append: {}
      key:
        simple: URL
      value:
        simple: '["https://www.1.com","https://www.2.com","https://www.3.com","https://www.4.com","https://www.5.com","https://www.6.com","https://www.7.com","https://www.8.com","https://www.9.com","https://www.10.com"]'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1385
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 44d7ba13-30c5-45fd-88d3-722e417861c0
    type: regular
    task:
      id: 44d7ba13-30c5-45fd-88d3-722e417861c0
      version: -1
      name: Try to add 10 URLs in one command
      description: |-
        Using the ID associated with the new category.
        Add 'https://test.com', 'http://dem.com' to category URL list.
      script: Forcepoint|||fp-add-address-to-category
      type: regular
      iscommand: true
      brand: Forcepoint
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      categoryID: {}
      categoryName:
        simple: ${Forcepoint.CategoryDetails.CategoryName}
      ips: {}
      urls:
        simple: ${URL}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 0c043dc4-9d94-4bf2-8cba-16c3df4b0aad
    type: condition
    task:
      id: 0c043dc4-9d94-4bf2-8cba-16c3df4b0aad
      version: -1
      name: Checking if add 10 URLS in one command?
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Forcepoint.AddAddressToCategory.Totals.AddedURLs
            iscontext: true
          right:
            value:
              simple: "10"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: a86a93e2-f868-414c-865f-5cef64dfaad6
    type: regular
    task:
      id: a86a93e2-f868-414c-865f-5cef64dfaad6
      version: -1
      name: try to delete 10 URL in one command
      description: Delete https://test.com from the category URL list
      script: Forcepoint|||fp-delete-address-from-category
      type: regular
      iscommand: true
      brand: Forcepoint
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      categoryID:
        simple: ${Forcepoint.CategoryDetails.CategoryID}
      categoryName: {}
      ips: {}
      urls:
        simple: ${URL}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1940
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: eed34fb1-d0f2-46e1-8ecc-2d08ede726e4
    type: condition
    task:
      id: eed34fb1-d0f2-46e1-8ecc-2d08ede726e4
      version: -1
      name: Checking if deleted 10 URLs in one command?
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Forcepoint.DeleteAddressesFromCategory.Totals.DeletedURLs
            iscontext: true
          right:
            value:
              simple: "10"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2110
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 67aaaf6b-5b3f-43f5-825d-9beb07576403
    type: title
    task:
      id: 67aaaf6b-5b3f-43f5-825d-9beb07576403
      version: -1
      name: Test run commands with array
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1270
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2360,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0
description: ''
