id: Google Safe Browsing Test
version: -1
name: Google Safe Browsing Test
description: Checking Google Safe Browsing integration by running it on both malicious
  and non-malicious URLs and checking the results
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 0b9ce673-5a1a-46f2-8346-a8fc0f78f041
    type: start
    task:
      id: 0b9ce673-5a1a-46f2-8346-a8fc0f78f041
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: a1981566-3992-435d-86a1-d35b01453069
    type: regular
    task:
      id: a1981566-3992-435d-86a1-d35b01453069
      version: -1
      name: Check non-malicious URL
      script: GoogleSafeBrowsing|||url
      type: regular
      iscommand: true
      brand: GoogleSafeBrowsing
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      url:
        simple: ${inputs.Non malicious URL}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 185
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 976c293d-6e2f-4462-824c-e38a7e888ff6
    type: condition
    task:
      id: 976c293d-6e2f-4462-824c-e38a7e888ff6
      version: -1
      name: Check if found malicious
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "9"
    scriptarguments:
      value: {}
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: URL.Malicious
            iscontext: true
    view: |-
      {
        "position": {
          "x": 450,
          "y": 346
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: fe30d613-13db-448c-8a19-6c5402ef42d6
    type: regular
    task:
      id: fe30d613-13db-448c-8a19-6c5402ef42d6
      version: -1
      name: Check malicious URL
      script: GoogleSafeBrowsing|||url
      type: regular
      iscommand: true
      brand: GoogleSafeBrowsing
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      url:
        simple: ${inputs.Malicious URL}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 619
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 5fc3b4aa-ad30-4221-85dd-d0868719d122
    type: condition
    task:
      id: 5fc3b4aa-ad30-4221-85dd-d0868719d122
      version: -1
      name: Check if found malicious
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: URL.Malicious
            iscontext: true
    view: |-
      {
        "position": {
          "x": 450,
          "y": 794
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: aebdf67a-2128-437d-8f6f-906d4d677503
    type: regular
    task:
      id: aebdf67a-2128-437d-8f6f-906d4d677503
      version: -1
      name: FAIL - False Positive
      script: RaiseError
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      error:
        simple: expected ${inputs.Non malicious URL} to not be malicious
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 889,
          "y": 524
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: d67e1e1e-bfc0-4255-816b-2e78d937acc3
    type: regular
    task:
      id: d67e1e1e-bfc0-4255-816b-2e78d937acc3
      version: -1
      name: FAIL - False Positive
      script: RaiseError
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      error:
        simple: expected ${inputs.Non malicious URL} to not be malicious
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 889,
          "y": 979
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1024,
        "width": 819,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: Malicious URL
  value:
    simple: http://testsafebrowsing.appspot.com/apiv4/ANY_PLATFORM/MALWARE/URL/
  required: false
  description: ""
  playbookInputQuery: null
- key: Non malicious URL
  value:
    simple: http://google.com
  required: false
  description: ""
  playbookInputQuery: null
outputs: []
fromversion: 5.0.0
