id: playbook7
version: -1
name: C&C Communication Hunting Playbook
system: true
description: A playbook to use the latest Threat Intelligence to hunt across your
  infrastructure and look for malicious C&C communications.
tasks:
- id: "1"
  taskid: 6bb644a4-ab7a-4f6c-82ff-c2543048a30d
  type: title
  task:
    id: 6bb644a4-ab7a-4f6c-82ff-c2543048a30d
    version: -1
    name: Prepare
- id: "2"
  taskid: 3608118f-e307-4a7e-8478-a74fe26a8747
  type: regular
  task:
    id: 3608118f-e307-4a7e-8478-a74fe26a8747
    version: -1
    name: Trigger an update of our IoC repository from all available Threat Intel
      sources
- id: "3"
  taskid: 2ec8a165-89f6-44b7-8329-8258b97edec4
  type: regular
  task:
    id: 2ec8a165-89f6-44b7-8329-8258b97edec4
    version: -1
    name: Retrieve fresh lists of C&C IoCs from repository
    description: Retrieve IoCs from repository into the incident context - IP addresses,
      domains, URLs
- id: "4"
  taskid: e0c2eca8-a6bd-4924-835b-4264c1d5a673
  type: title
  task:
    id: e0c2eca8-a6bd-4924-835b-4264c1d5a673
    version: -1
    name: Hunt
- id: "5"
  taskid: efa206e7-f25b-44fe-8c31-8a8a8b322336
  type: regular
  task:
    id: efa206e7-f25b-44fe-8c31-8a8a8b322336
    version: -1
    name: Query netflow records for traffic to C&C IPs
    description: Query the data repository where netflow records are continuously
      aggregated.
- id: "6"
  taskid: 4ddbe71f-9a61-4f7c-8dd4-50673f386a1a
  type: regular
  task:
    id: 4ddbe71f-9a61-4f7c-8dd4-50673f386a1a
    version: -1
    name: Search web proxy logs for C&C URLs
- id: "7"
  taskid: bbefe0d0-cde1-4f50-8bdc-f469f3c80264
  type: regular
  task:
    id: bbefe0d0-cde1-4f50-8bdc-f469f3c80264
    version: -1
    name: Search the organization's DNS server logs for C&C domains
- id: "8"
  taskid: 388ef341-1a5b-4352-8328-2af51d604196
  type: regular
  task:
    id: 388ef341-1a5b-4352-8328-2af51d604196
    version: -1
    name: Search Endpoint monitoring infrastructure for communication with C&C IPs
- id: "9"
  taskid: d36f548c-3e55-42e5-8059-73e1adf0371e
  type: regular
  task:
    id: d36f548c-3e55-42e5-8059-73e1adf0371e
    version: -1
    name: Search Firewall and IPS logs for C&C IPs
    description: Check if any traffic was attempted to a C&C IP and blocked by our
      Network Security controls such as Firewalls and IPSs
- id: "10"
  taskid: e8beb59e-d7fd-4bc4-8c5d-f29bfa3370ce
  type: title
  task:
    id: e8beb59e-d7fd-4bc4-8c5d-f29bfa3370ce
    version: -1
    name: Validate findings
- id: "11"
  taskid: 20253d8e-c1d5-4918-82d1-aeac6837d061
  type: condition
  task:
    id: 20253d8e-c1d5-4918-82d1-aeac6837d061
    version: -1
    name: Did we uncover any suspected C&C communication?
  condition:
    "no": []
    "yes":
    - id: "12"
      taskid: 66696f7e-2a82-4d91-880d-a68502b214a5
      type: regular
      task:
        id: 66696f7e-2a82-4d91-880d-a68502b214a5
        version: -1
        name: Review correlations with past investigations in case management / incident
          tracking
        description: Have any of our IoCs appeared in a past investigation? What did
          we know about them then, and what was the conclusion?
    - id: "13"
      taskid: 45237e6a-0780-41c5-8f55-d6aeefda3db1
      type: regular
      task:
        id: 45237e6a-0780-41c5-8f55-d6aeefda3db1
        version: -1
        name: Review reputation data for each indicator
        description: Review displayed reputation data for IPs, domains and URLs using
          all reputation sources
    - id: "14"
      taskid: 2a31590b-f37c-409c-8177-c173b5262586
      type: condition
      task:
        id: 2a31590b-f37c-409c-8177-c173b5262586
        version: -1
        name: Is PassiveTotal Available?
        script: IsIntegrationAvailable
      condition:
        "no": []
        "yes":
        - id: "15"
          taskid: 0f052e94-da1b-49b1-898f-4de332126b3f
          type: regular
          task:
            id: 0f052e94-da1b-49b1-898f-4de332126b3f
            version: -1
            name: Review PassiveTotal enrichment data for the indicators
            description: Has PassiveTotal marked the domain as "ever compromised"?
              Does it associate the domain with a known malware?
      scriptarguments:
        brandname: passivetotal
      results:
      - brandInstances
    - id: "16"
      taskid: f82098d5-28a7-400c-8f0d-cd073dfdccde
      type: condition
      task:
        id: f82098d5-28a7-400c-8f0d-cd073dfdccde
        version: -1
        name: Is CrowdStrike Intel Available?
        script: IsIntegrationAvailable
      condition:
        "no": []
        "yes":
        - id: "17"
          taskid: 2676407a-39f4-4dae-8f1e-b72e52bcd409
          type: regular
          task:
            id: 2676407a-39f4-4dae-8f1e-b72e52bcd409
            version: -1
            name: Get and review CrowdStrike indicator information
      scriptarguments:
        brandname: csintel
      results:
      - brandInstances
    - id: "18"
      taskid: 1127e16d-2f20-4090-89a2-e000f2cd9461
      type: condition
      task:
        id: 1127e16d-2f20-4090-89a2-e000f2cd9461
        version: -1
        name: Do the found IoCs include domain names?
      condition:
        "no": []
        "yes":
        - id: "19"
          taskid: a71b6494-370c-486a-84ac-1a3c58118c11
          type: regular
          task:
            id: a71b6494-370c-486a-84ac-1a3c58118c11
            version: -1
            name: Review the domains' Whois information
        - id: "20"
          taskid: caae4dd9-e7c0-458c-84a9-90db5c2e6fac
          type: regular
          task:
            id: caae4dd9-e7c0-458c-84a9-90db5c2e6fac
            version: -1
            name: Retrieve DNS history for these domains
        - id: "21"
          taskid: c91818be-5898-46ee-8263-a2f531216e5e
          type: regular
          task:
            id: c91818be-5898-46ee-8263-a2f531216e5e
            version: -1
            name: Review IP reputation for the IPs to which this domain resolved at
              the time
    - id: "22"
      taskid: 5823c9d5-90cc-41cf-87c5-7b94b692f96e
      type: regular
      task:
        id: 5823c9d5-90cc-41cf-87c5-7b94b692f96e
        version: -1
        name: Summarize the list of validated malicious indicators
- id: "23"
  taskid: b7ee6752-2787-4142-8802-0d3ae23033c7
  type: title
  task:
    id: b7ee6752-2787-4142-8802-0d3ae23033c7
    version: -1
    name: Respond
- id: "24"
  taskid: 9ac6e273-1fa9-42e3-8367-031ce8a663f3
  type: condition
  task:
    id: 9ac6e273-1fa9-42e3-8367-031ce8a663f3
    version: -1
    name: Have any machines been confirmed as compromised?
  condition:
    "no": []
    "yes":
    - id: "25"
      taskid: 7b632ce1-d607-40a1-8704-1097f5df2e72
      type: regular
      task:
        id: 7b632ce1-d607-40a1-8704-1097f5df2e72
        version: -1
        name: Isolate compromised hosts from network
    - id: "26"
      taskid: 1a83ba02-3043-423b-8f6e-b91e3ed5de09
      type: regular
      task:
        id: 1a83ba02-3043-423b-8f6e-b91e3ed5de09
        version: -1
        name: Disable compromised AD user account(s)
        description: Block access to the compromised user account in AD pending investigation
          and cleanup, after which the account will be reinstated by an Active Directory
          administrator with the required permissions.
    - id: "27"
      taskid: bd9b46ea-07eb-46ee-8308-46888a11640b
      type: regular
      task:
        id: bd9b46ea-07eb-46ee-8308-46888a11640b
        version: -1
        name: Lock / Rotate any other compromised accounts, keys and credentials
        description: If the machine contained any authentication keys, accounts to
          internal company resources and information systems, these should be locked
          and revoked, and reinstated later with new passwords.
    - id: "28"
      taskid: 718dba61-5ced-4f7f-87d3-2e7f464fa34d
      type: condition
      task:
        id: 718dba61-5ced-4f7f-87d3-2e7f464fa34d
        version: -1
        name: Is Slack Available?
        script: IsIntegrationAvailable
      condition:
        "no":
        - id: "29"
          taskid: e7c70fba-f94f-4a02-8041-ef0bbf35baf0
          type: regular
          task:
            id: e7c70fba-f94f-4a02-8041-ef0bbf35baf0
            version: -1
            name: Retrieve the user's phone number from Active Directory
        - id: "30"
          taskid: 1fbda83c-a5db-4196-8965-dc37eb7b7ecc
          type: condition
          task:
            id: 1fbda83c-a5db-4196-8965-dc37eb7b7ecc
            version: -1
            name: Is Twilio Available?
            script: IsIntegrationAvailable
          condition:
            "no":
            - id: "31"
              taskid: dcf67394-61f2-49bb-8e0d-bc4fe64777b8
              type: regular
              task:
                id: dcf67394-61f2-49bb-8e0d-bc4fe64777b8
                version: -1
                name: Call the user and tell them that their machine is being isolated
                  and investigated
            "yes":
            - id: "32"
              taskid: 322e404d-bfed-49fd-824d-67dc96c95596
              type: regular
              task:
                id: 322e404d-bfed-49fd-824d-67dc96c95596
                version: -1
                name: SMS the user that their machine is being isolated and investigated
          scriptarguments:
            brandname: twilio
          results:
          - brandInstances
        "yes":
        - id: "33"
          taskid: 3c17b8bd-e79e-4a02-8b1d-83e10fd749a8
          type: regular
          task:
            id: 3c17b8bd-e79e-4a02-8b1d-83e10fd749a8
            version: -1
            name: Tell the user on Slack that their machine is being isolated and
              investigated
      results:
      - brandInstances
    - id: "34"
      taskid: c43c578d-8337-42b4-8fbc-73e178f6d0d5
      type: regular
      task:
        id: c43c578d-8337-42b4-8fbc-73e178f6d0d5
        version: -1
        name: Open separate incidents to further investigate each compromised host
- id: "35"
  taskid: 789a66bc-3116-4084-8c04-61b840d818ce
  type: title
  task:
    id: 789a66bc-3116-4084-8c04-61b840d818ce
    version: -1
    name: Remediate and Wrap up
- id: "36"
  taskid: 6f288fd3-3fb2-49af-8036-96f1063cd098
  type: condition
  task:
    id: 6f288fd3-3fb2-49af-8036-96f1063cd098
    version: -1
    name: Have the machines been cleaned successfully?
  condition:
    "no":
    - id: "37"
      taskid: ba3b890e-71b4-4f4d-8fd1-b33f295fd72e
      type: regular
      task:
        id: ba3b890e-71b4-4f4d-8fd1-b33f295fd72e
        version: -1
        name: Open a ticket for IT to reimage the machine
    "yes":
    - id: "38"
      taskid: c3330605-13ed-4282-8d71-6150364e16d2
      type: regular
      task:
        id: c3330605-13ed-4282-8d71-6150364e16d2
        version: -1
        name: Restore network access for cleaned up hosts
- id: "39"
  taskid: bd76719e-c055-464d-868f-da361e6d134c
  type: regular
  task:
    id: bd76719e-c055-464d-868f-da361e6d134c
    version: -1
    name: Reinstate locked user accounts with new credentials
- id: "40"
  taskid: a80fd4c5-d1b2-4095-88a8-242e4ae17db5
  type: condition
  task:
    id: a80fd4c5-d1b2-4095-88a8-242e4ae17db5
    version: -1
    name: Is Slack Available?
    script: IsIntegrationAvailable
  condition:
    "no":
    - id: "41"
      taskid: b195772e-ba3d-4283-8cd5-2103d953285d
      type: regular
      task:
        id: b195772e-ba3d-4283-8cd5-2103d953285d
        version: -1
        name: Retrieve the user's phone number from Active Directory
    - id: "42"
      taskid: 989d8d47-033c-4d47-89a6-d005eb7f0ffc
      type: condition
      task:
        id: 989d8d47-033c-4d47-89a6-d005eb7f0ffc
        version: -1
        name: Is Twilio Available?
        script: IsIntegrationAvailable
      condition:
        "no":
        - id: "43"
          taskid: 2c7bfecc-9b5d-43ba-8e1b-a35265824fef
          type: regular
          task:
            id: 2c7bfecc-9b5d-43ba-8e1b-a35265824fef
            version: -1
            name: Call the user and tell them that their accounts have been reinstated
        "yes":
        - id: "44"
          taskid: 59e491df-f254-42fe-8e01-5956b8eba874
          type: regular
          task:
            id: 59e491df-f254-42fe-8e01-5956b8eba874
            version: -1
            name: SMS the user that their account has been reinstated
            description: Optionally - include the temporary random password generated
              for the account. The user will have to choose a new password on first
              login.
      scriptarguments:
        brandname: twilio
      results:
      - brandInstances
    "yes":
    - id: "45"
      taskid: ed705bda-b8c5-4be1-84f5-5dd6ea5093e4
      type: regular
      task:
        id: ed705bda-b8c5-4be1-84f5-5dd6ea5093e4
        version: -1
        name: Notify the user via Slack that their account has been reinstated
        description: Optionally - include the temporary random password generated
          for the account. The user will have to choose a new password on first login.
        script: SlackSend
  scriptarguments:
    brandname: slack
  results:
  - brandInstances
- id: "46"
  taskid: 1a2dbd58-f17d-437d-8573-54a8339d3ccb
  type: regular
  task:
    id: 1a2dbd58-f17d-437d-8573-54a8339d3ccb
    version: -1
    name: Deploy validated IoCs with high confidence rating against future attacks
- id: "47"
  taskid: e1c5da88-1515-496c-8501-1b5b4c504f93
  type: regular
  task:
    id: e1c5da88-1515-496c-8501-1b5b4c504f93
    version: -1
    name: Share the validated IoCs with partner organizations
    description: Include any information gleaned about attribution to a known threat
      actor, especially if the actor is known to be targeting your industrial sector.
- id: "48"
  taskid: a5a8e072-2d12-46ad-8448-1c958924aa4d
  type: regular
  task:
    id: a5a8e072-2d12-46ad-8448-1c958924aa4d
    version: -1
    name: Issue report to CISO by email
