id: playbook1
version: -1
name: Malware Playbook - Manual
description: Master playbook for malware incidents. This playbook is a manual playbook.
tags:
- Virus
- Malware
tasks:
- id: "1"
  taskid: f61f3880-e5f6-4a41-8af8-3349e3ebffff
  type: title
  task:
    id: f61f3880-e5f6-4a41-8af8-3349e3ebffff
    version: -1
    name: Engage
    issystemtask: true
- id: "2"
  taskid: 1bf3408d-bfcc-4030-8406-126c9514ee5b
  type: regular
  task:
    id: 1bf3408d-bfcc-4030-8406-126c9514ee5b
    version: -1
    name: Set initial incident context
    script: IncidentToContext
  results:
  - Label/Application
  - Label/Database
  - Label/Directory
  - Label/Email
  - Label/Email/cc
  - Label/Email/from
  - Label/Email/format
  - Label/Email/html
  - Label/Email/text
  - Label/Email/subject
  - Label/Email/attachments
  - Label/Email/headers
  - Label/IP
  - Label/System
  - Label/URL
  - Label/User
  - Label/Brand
  - Label/Instance
  - id
  - created
  - modified
  - occurred
  - dueDate
  - name
  - owner
  - type
  - severity
  - phase
  - status
  - details
  - score
- id: "3"
  taskid: d69a6289-b692-404c-8f90-d37d72aa265c
  type: regular
  task:
    id: d69a6289-b692-404c-8f90-d37d72aa265c
    version: -1
    name: Notify management chain
    description: 'Notify appropriate people inside the organization. '
    issystemtask: true
- id: "4"
  taskid: 21cb9178-78a0-4610-801f-3bc5f808e4a2
  type: regular
  task:
    id: 21cb9178-78a0-4610-801f-3bc5f808e4a2
    version: -1
    name: Initial triage
    description: 1. Make sure that there is relevant information in the incident -
      system name, end user name and initial severity as reported.
    issystemtask: true
- id: "5"
  taskid: cd85115e-4379-4319-853b-f518e9aa98bc
  type: regular
  task:
    id: cd85115e-4379-4319-853b-f518e9aa98bc
    version: -1
    name: Assess severity
    description: 'Based on the end user affected, and other information assess and
      change the severity if needed. '
    issystemtask: true
- id: "6"
  taskid: 8135a8aa-6d2c-4cf1-80c4-c5cf4bf136a8
  type: regular
  task:
    id: 8135a8aa-6d2c-4cf1-80c4-c5cf4bf136a8
    version: -1
    name: Assign and involve appropriate personnel
    description: 'Invite the relevant users for investigation - malware expert and
      network experts if needed. '
    issystemtask: true
- id: "7"
  taskid: 6a8d2675-34a0-412b-8835-40e4f8a24849
  type: title
  task:
    id: 6a8d2675-34a0-412b-8835-40e4f8a24849
    version: -1
    name: 'Investigation Step 1: Initial Inspection'
    issystemtask: true
- id: "8"
  taskid: 2820cd55-abce-480a-80db-484a2d4a817c
  type: regular
  task:
    id: 2820cd55-abce-480a-80db-484a2d4a817c
    version: -1
    name: Obtain phishing email from the user
    description: 'Get the suspected email from end user and attach it to the investigation.
      Document the subject, details of the email and other pieces in the investigation. '
    issystemtask: true
- id: "9"
  taskid: c31637b7-02f1-4868-865c-ca5d5805c46a
  type: regular
  task:
    id: c31637b7-02f1-4868-865c-ca5d5805c46a
    version: -1
    name: Collect volatile system data
    description: 'Collect system data like running processes, network connections
      and files changed. '
    issystemtask: true
- id: "10"
  taskid: 05339003-481a-4ba6-85cd-a4fc9a2d15a0
  type: regular
  task:
    id: 05339003-481a-4ba6-85cd-a4fc9a2d15a0
    version: -1
    name: Create memory dump of the system
    description: 'In addition to a full backup create a memory dump of the system. '
    issystemtask: true
- id: "11"
  taskid: 6754484c-6891-45be-80f3-8ca596286a8b
  type: regular
  task:
    id: 6754484c-6891-45be-80f3-8ca596286a8b
    version: -1
    name: Create backup of affected systems
    description: Create complete backup of affected systems for recovery and forensics.
    issystemtask: true
- id: "12"
  taskid: 35d8737d-3dec-4a0b-86e1-9d421d3996b4
  type: regular
  task:
    id: 35d8737d-3dec-4a0b-86e1-9d421d3996b4
    version: -1
    name: Review antivirus logs for the affected systems
    issystemtask: true
- id: "13"
  taskid: 2327241b-ffc0-4a03-8af2-4654b53cbe2a
  type: regular
  task:
    id: 2327241b-ffc0-4a03-8af2-4654b53cbe2a
    version: -1
    name: Research other malware databases
    description: "Review recently changed and created files on the system against
      other malware databases (Virustotal, XFE). \n"
    issystemtask: true
- id: "14"
  taskid: b3510d6b-6202-4ee4-844f-c63f0f8a5789
  type: regular
  task:
    id: b3510d6b-6202-4ee4-844f-c63f0f8a5789
    version: -1
    name: Review registry for suspicious activity (windows)
    description: 'Review the registry for suspicious activity in runonce etc. '
    issystemtask: true
- id: "15"
  taskid: 43f9a58e-14e8-422b-83c4-38689773be3f
  type: regular
  task:
    id: 43f9a58e-14e8-422b-83c4-38689773be3f
    version: -1
    name: Run IOC database against the affected system
    description: 'Run the recent IOC databases against the reported system. '
    issystemtask: true
- id: "16"
  taskid: 3233684b-e31c-4ad8-86c4-274a6205208c
  type: regular
  task:
    id: 3233684b-e31c-4ad8-86c4-274a6205208c
    version: -1
    name: Analyze network traffic for signs of intrusion
    description: Analyze the network traffic from/to this system for signs of intrusion.
    issystemtask: true
- id: "17"
  taskid: 5f142333-7e70-4884-8fd6-aadc40fdfa54
  type: regular
  task:
    id: 5f142333-7e70-4884-8fd6-aadc40fdfa54
    version: -1
    name: Analyze network traffic for malware activity
    description: Analyze the network traffic from/to this system for malware activity
    issystemtask: true
- id: "18"
  taskid: ce404b7b-103c-46cb-8ee3-5ce318aee2bc
  type: regular
  task:
    id: ce404b7b-103c-46cb-8ee3-5ce318aee2bc
    version: -1
    name: Correlate network and file data against threat intelligence
    description: |
      Research current threat intelligence for network and file activity
    issystemtask: true
- id: "19"
  taskid: 7d3de1a4-dabf-485b-87d1-b4b42de754dd
  type: regular
  task:
    id: 7d3de1a4-dabf-485b-87d1-b4b42de754dd
    version: -1
    name: Look for traces of network sniffers
    issystemtask: true
- id: "20"
  taskid: fcef2636-23ce-4352-852e-13e7b513ceef
  type: regular
  task:
    id: fcef2636-23ce-4352-852e-13e7b513ceef
    version: -1
    name: Look for system file and registry (win) modification
    description: "Look for modification made to system and configuration files. Document
      recently modified system files. \n"
    issystemtask: true
- id: "21"
  taskid: 1aa0c9db-5d38-414c-802c-7605f0d380da
  type: regular
  task:
    id: 1aa0c9db-5d38-414c-802c-7605f0d380da
    version: -1
    name: Analyze file samples collected with a malware analysis sandbox
    description: 'Run the analysis on file samples collected from affected system. '
    issystemtask: true
- id: "22"
  taskid: e749b793-b7c2-4628-8101-2927e20796b9
  type: regular
  task:
    id: e749b793-b7c2-4628-8101-2927e20796b9
    version: -1
    name: Run memory analysis on the system memory
    description: 'Use SIFT tools for memory analysis to look at running processes
      and recently closed network connections. '
    issystemtask: true
- id: "23"
  taskid: 303fc207-916d-4057-8717-3c5e38f945d5
  type: regular
  task:
    id: 303fc207-916d-4057-8717-3c5e38f945d5
    version: -1
    name: Research current intelligence against memory analysis
    description: 'Research the current threat intelligence against findings in memory
      analysis. '
    issystemtask: true
- id: "24"
  taskid: 75065aaa-08b8-421c-82fb-ebb78296c3c8
  type: regular
  task:
    id: 75065aaa-08b8-421c-82fb-ebb78296c3c8
    version: -1
    name: Send status update
    description: Update management team about status of incident
    issystemtask: true
- id: "25"
  taskid: 5e48a7f1-8c3d-4472-8edd-43ad2ef061ce
  type: condition
  task:
    id: 5e48a7f1-8c3d-4472-8edd-43ad2ef061ce
    version: -1
    name: Was malware found?
    issystemtask: true
  condition:
    "no":
    - id: "26"
      taskid: 79732f56-83e8-428c-8a96-c9f0e853b45f
      type: regular
      task:
        id: 79732f56-83e8-428c-8a96-c9f0e853b45f
        version: -1
        name: Inform user that no malware was found
        issystemtask: true
    "yes":
    - id: "27"
      taskid: 9a73f01e-6096-4daf-80d3-0b671e74f619
      type: regular
      task:
        id: 9a73f01e-6096-4daf-80d3-0b671e74f619
        version: -1
        name: Report malware sample to AV vendor
        issystemtask: true
- id: "28"
  taskid: bc465242-756c-44ad-8546-b004ca98190c
  type: title
  task:
    id: bc465242-756c-44ad-8546-b004ca98190c
    version: -1
    name: Data Leak Assessment
    issystemtask: true
- id: "29"
  taskid: 77134e96-d810-4fe9-8573-0dae9701905c
  type: condition
  task:
    id: 77134e96-d810-4fe9-8573-0dae9701905c
    version: -1
    name: Was any sensitive information leaked?
    issystemtask: true
  condition:
    "no": []
    "yes":
    - id: "30"
      taskid: 79473708-5b11-44ae-86ad-1f05ec3ae75c
      type: regular
      task:
        id: 79473708-5b11-44ae-86ad-1f05ec3ae75c
        version: -1
        name: Notify Public Relations (PR) team
        issystemtask: true
- id: "31"
  taskid: 2b290909-b729-46a4-8c09-212bee8f6094
  type: title
  task:
    id: 2b290909-b729-46a4-8c09-212bee8f6094
    version: -1
    name: Respond
    issystemtask: true
- id: "32"
  taskid: 5b96fdcb-14af-434b-8c89-ebbb3b344145
  type: regular
  task:
    id: 5b96fdcb-14af-434b-8c89-ebbb3b344145
    version: -1
    name: Notify affected user
    description: Notify affected user about the outcome of investigation.
    issystemtask: true
- id: "33"
  taskid: b32992a7-f5e0-4b95-8dd2-5c70e938c715
  type: regular
  task:
    id: b32992a7-f5e0-4b95-8dd2-5c70e938c715
    version: -1
    name: Remove temporary containment measures
    description: Remove the temporary containment measures that were placed.
    issystemtask: true
- id: "34"
  taskid: 35c0d3b2-d9cd-460c-88be-6d7a229e9906
  type: regular
  task:
    id: 35c0d3b2-d9cd-460c-88be-6d7a229e9906
    version: -1
    name: Provide end-user remediation guidance and link to training
    issystemtask: true
- id: "35"
  taskid: f68ec944-041d-4288-80fd-d4593bceb52b
  type: condition
  task:
    id: f68ec944-041d-4288-80fd-d4593bceb52b
    version: -1
    name: Is the identified malware known? (with automated remediation steps)
    issystemtask: true
  condition:
    "no":
    - id: "36"
      taskid: f13d62e8-15a2-4240-8245-9537c0c7aa83
      type: regular
      task:
        id: f13d62e8-15a2-4240-8245-9537c0c7aa83
        version: -1
        name: Document manual remediation steps
        issystemtask: true
    "yes":
    - id: "37"
      taskid: 91223da8-3e5b-432e-85d6-b05a8e614f83
      type: regular
      task:
        id: 91223da8-3e5b-432e-85d6-b05a8e614f83
        version: -1
        name: Trigger remediation scripts
        issystemtask: true
- id: "38"
  taskid: 36ba1145-5eb5-4bc4-85f6-d5c9f4495cca
  type: condition
  task:
    id: 36ba1145-5eb5-4bc4-85f6-d5c9f4495cca
    version: -1
    name: Was remediation successful?
    issystemtask: true
  condition:
    "no":
    - id: "39"
      taskid: c56d39eb-e583-4183-8b18-12e9d0547c17
      type: regular
      task:
        id: c56d39eb-e583-4183-8b18-12e9d0547c17
        version: -1
        name: Reimage the entire system and restore from backup
        issystemtask: true
    "yes": []
system: true